// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/exams/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/exams/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/exams/[id].patch').default>>>>
    }
    '/api/admin/exams': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/exams/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/exams/index.post').default>>>>
    }
    '/api/admin/questions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/questions/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/questions/[id].patch').default>>>>
    }
    '/api/admin/questions/:id/approve': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/questions/[id]/approve.post').default>>>>
    }
    '/api/admin/questions/bulk-approve': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/questions/bulk-approve.post').default>>>>
    }
    '/api/admin/questions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/questions/index.post').default>>>>
    }
    '/api/admin/reset-device': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/reset-device.post').default>>>>
    }
    '/api/admin/review/pending': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/review/pending.get').default>>>>
    }
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/admin/subscriptions/:id/approve': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/subscriptions/[id]/approve.post').default>>>>
    }
    '/api/admin/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/upload.post').default>>>>
    }
    '/api/admin/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].patch').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/index.get').default>>>>
    }
    '/api/auth/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...]').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/session': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/session.get').default>>>>
    }
    '/api/exams/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exams/[id].get').default>>>>
    }
    '/api/exams/:id/questions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exams/[id]/questions.get').default>>>>
    }
    '/api/exams': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exams/index.get').default>>>>
    }
    '/api/leaderboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leaderboard.get').default>>>>
    }
    '/api/sessions/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions/[id].patch').default>>>>
    }
    '/api/sessions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions/index.post').default>>>>
    }
    '/api/sessions/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions/me.get').default>>>>
    }
    '/api/subscription/purchase': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subscription/purchase.post').default>>>>
    }
    '/api/subscription/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subscription/status.get').default>>>>
    }
    '/api/user/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/me.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/me.patch').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}